- hosts: localhost
  connection: local
  vars:
    # Define distro variable with a default value or leave it undefined
    # to be set via command line. If not set, it will default to 'arch'.
    distro: "{{ distro | default('arch') }}"
  roles:
    - role: arch
      when: distro == 'arch'
    - role: fedora
      when: distro == 'fedora'
    - role: petermosmans.customize-gnome
      vars:
        gnome_user: 'adam'
        gnome_extentions:
          - url: 'https://github.com/ubuntu/gnome-shell-extension-appindicator/archive/refs/tags/v46.zip'
            name: 'appindicators'
            enabled: yes
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
