- name: User Bootstrap
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Ensure ansible_svc user exists and has sudoers
      ansible.builtin.import_role:
        name: user_management
  roles:
    - role: arch
