---

- name: add RPMFusion free key
  ansible.builtin.rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    state: present

- name: add RPMFusion nonfree key
  ansible.builtin.rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
    state: present

- name: add RPMFusion free repo
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present

- name: add RPMFusion nonfree repo
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present

### Update packages
- name: update packages
  ansible.builtin.dnf:
    name: '*'
    update_cache: yes
    state: latest

- name: media codecs
  ansible.builtin.dnf:
    
### Install packages

- name: Install python3-pip
  ansible.builtin.dnf:
    name:
      - python3-pip
      - python3-psutil
      - tmux
      - vim
      - mpv
      - kernel-devel
      - flatpak
      - cronie
      - cronie-anacron
    state: present
    update_cache: true

### Install github python module

- name: install github python module
  ansible.builtin.pip:
    name:
      - "github3.py>=1.0.0a3"
    state: present
    executable: /usr/bin/pip3

### Install vscode

- name: Install MS RPM key
  ansible.builtin.rpm_key:
    key: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add MS VSCode RPM repo
  ansible.builtin.yum_repository:
    name: vscode
    baseurl:
      - "https://packages.microsoft.com/yumrepos/vscode"
    enabled: true
    gpgcheck: true
    description: "VSCode Repo"
    gpgkey:
      - "https://packages.microsoft.com/keys/microsoft.asc"

- name: Install vscode packages
  ansible.builtin.dnf:
    name: code
    state: present
    update_cache: true

### Install Microsoft Teams
- name: Add MS Teams RPM Repo
  ansible.builtin.yum_repository:
    name: ms-teams
    baseurl:
      - "https://packages.microsoft.com/yumrepos/ms-teams"
    enabled: true
    gpgcakey: true
    description: "MS Teams Repo"
    gpgkey:
      - "https://packages.microsoft.com/keys/microsoft.asc"

- name: Install MS Teams RPM
  ansible.builtin.dnf:
    name: teams
    state: present
    update_cache: true

### Install git credential manager

- name: get latest gcm core binary version
  community.general.github_release:
    repo: git-credential-manager
    user: GitCredentialManager
    action: latest_release
  register: gcm_latest

- name: Download latest gcm core binary
  ansible.builtin.unarchive:
    src: "https://github.com/GitCredentialManager/git-credential-manager/releases/download/{{ gcm_latest['tag'] }}/gcm-linux_amd64.{{ gcm_latest['tag'] | regex_replace('^v','') }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true

- name: Configure GCM Core
  become_user: adam
  ansible.builtin.command:
    cmd: git-credential-manager configure

### Install Flathub


- name: Install Flathub for users
  community.general.flatpak_remote:
    name: flathub-org
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    state: present
    method: system   

### Install most-used Flatpaks

- name: Install Desktop Flatpaks
  become_user: adam
  community.general.flatpak:
    name:
      - org.telegram.desktop
      - tv.plex.PlexDesktop
      - com.discordapp.discord
      - com.mattermost.Desktop
      - us.zoom.Zoom
      - com.mattjakeman.ExtensionManager
    state: present
    remote: flathub-org

### Set mpv config

- name: create mpv config directory
  become_user: adam
  ansible.builtin.file:
    path: "~/.config/mpv/"
    owner: adam
    group: adam
    state: directory
    mode: '0755'

- name: Set HWDEC in mpv config
  become_user: adam
  ansible.builtin.template:
    src: "mpv.conf.j2"
    dest: "~/.config/mpv/mpv.conf"

### Set wallpaper

- name: Copy wallpaper
  ansible.builtin.copy:
    src: "wallpaper.jpg"
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root

- name: Set light wallpaper
  become_user: adam
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: Set dark wallpaper
  become_user: adam
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: set wallpaper position
  become_user: adam
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

  ### Add ansible-pull automation

- name: add ansible user
  user:
    name: velociraptor
    system: yes

- name: set up sudo for ansible user
  copy:
    src: sudoer_velociraptor
    dest: /etc/sudoers.d/velociraptor
    owner: root
    group: root
    mode: 0440

- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: velociraptor
    minute: "*/10"
    job: ansible-pull -o -U https://github.com/argrubbs/ansible_desktop.git
