- name: Create dedicated ansible deployment user
  ansible.builtin.user:
    name: ansible_svc
    shell: /sbin/nologin
    system: true
    create_home: false
    state: present
  become: true

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
  become: true

- name: Allow the `aur_builder` user to run `pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s" # Corrected from 'viaansi'
    mode: "0440"
  become: true

- name: Set up NOPASSWD sudo for ansible service user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/10-ansible-svc
    line: 'ansible_svc ALL=(ALL) NOPASSWD: ALL'
    create: true
    validate: 'visudo -cf %s'
    mode: '0440'
  become: true

- name: Define allowed sudoers files
  ansible.builtin.set_fact:
    allowed_sudoers_files:
      - '10-ansible-svc'
      - '11-install-aur_builder'

- name: Find unauthorized sudoers files
  ansible.builtin.find:
    paths: /etc/sudoers.d
    file_type: file
    recurse: false
  register: unauthorized_sudoers_files
  become: true

- name: Remove unauthorized sudoers.d files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ unauthorized_sudoers_files.files }}"
  when: item.path | basename not in allowed_sudoers_files
  become: true
