---
### Enable ASUS tools
# - name: Enable asus-linux pacman repo
#   become: true
#   become_method: ansible.builtin.sudo
#   ansible.builtin.blockinfile:
#     path: "/etc/pacman.conf"
#     block: |
#       [g14]
#       SigLevel = DatabaseNever Optional TrustAll
#       Server = https://arch.asus-linux.org

- name: Refresh pacman cache
  become: true
  become_method: ansible.builtin.sudo
  community.general.pacman:
    update_cache: true

- name: Create dev folder
  ansible.builtin.file:
    path: /home/adam/dev
    state: directory
    mode: "0755"
    owner: adam
    group: adam

- name: Clone yay AUR helper
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/home/adam/dev/yay"
    update: true

- name: Build and install yay
  ansible.builtin.command:
    chdir: "/home/adam/dev/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: "/usr/bin/yay"

- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s" # Corrected from 'viaansi'
    mode: "0440"

### Install packages

- name: Install essential packages
  become: true
  become_method: ansible.builtin.sudo
  community.general.pacman:
    name:
      - python-pip
      - python-psutil
      - tmux
      - vim
      - mpv
      - base-devel
      - flatpak
      - steam
      - wine
      - code
      - lutris
      - spectacle
      - remmina
      - rsync
      - kaccounts-providers
      - firefox
      - gamemode
      - okular
    state: present
    update_cache: true

# - name: Install asus-linux tools
#   become: true
#   become_method: ansible.builtin.sudo
#   community.general.pacman:
#     name: ["asusctl", "supergfxctl", "rog-control-center"]
#     state: present

# - name: Enable supergfxd
#   become: true
#   become_method: ansible.builtin.sudo
#   ansible.builtin.systemd:
#     name: "supergfxd"
#     state: started
#     daemon_reload: true
#     enabled: true

- name: Install common AUR packages
  kewlfft.aur.aur:
    name:
      - amf-amdgpu-pro
      - steamtinkerlaunch
      - obs-studio-amf
      - mangohud
      - lib32-mangohud
      - gamemode
      - obs-vkcapture-git
      - lib32-obs-vkcapture-git
      - 1password
      - 1password-cli
    use: yay
    state: present
    extra_args: ['--noconfirm']
  become_user: aur_builder
  become: true
  become_method: ansible.builtin.sudo

### Set environment variables

- name: Set env variables
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.blockinfile:
    path: "/etc/environment"
    state: present
    block: |
      KWIN_DRM_NO_DIRECT_SCANOUT=1
      MOZ_ENABLE_WAYLAND=1
      EDITOR=vim

### Install github python module
- name: INstall virualenvwrapper
  become: true
  become_method: ansible.builtin.sudo
  community.general.pacman:
    name: python-virtualenvwrapper
    state: present

- name: Add virtualenvwrapper to bashrc
  ansible.builtin.blockinfile:
    path: "/home/adam/.bashrc"
    state: present
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME/Devel
      source /usr/local/bin/virtualenvwrapper.sh

- name: Set up 1password-cli bash-completion
  ansible.builtin.blockinfile:
    path: "/home/adam/.bashrc"
    state: present
    block: |
      source <(op completion bash)

### Install most-used Flatpaks

- name: Install Desktop Flatpaks
  community.general.flatpak:
    name:
      - org.telegram.desktop
      - tv.plex.PlexDesktop
      - com.discordapp.Discord
      - com.mattermost.Desktop
      - us.zoom.Zoom
      - com.mattjakeman.ExtensionManager
    state: present
    remote: flathub

### Set mpv config

- name: Create mpv config directory
  ansible.builtin.file:
    path: "~/.config/mpv/"
    owner: adam
    group: adam
    state: directory
    mode: "0755"

- name: Set HWDEC in mpv config
  ansible.builtin.template:
    src: "mpv.conf.j2"
    dest: "~/.config/mpv/mpv.conf"
    mode: "0755"
    owner: adam
    group: adam

### Set wallpaper

- name: Copy wallpaper
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.copy:
    src: "wallpaper.jpg"
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root
    mode: "0755"

### Enable trim
### Enable SSD Trim
- name: SSD Trim
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.systemd:
    name: fstrim.timer
    enabled: true
